project_id = "rdsnujlzytslijpapyei"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "https://rdsnujlzytslijpapyei.supabase.co"
additional_redirect_urls = ["https://lovable.app", "https://lovable.dev", "https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322
shadow_port = 54320
major_version = 15

[functions.pipeline-run]
verify_jwt = false

[edge_runtime]
policy = "per_worker"
inspector_port = 8083